name: 'Auto Assign Reviewers'

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        uses: ahmadnassri/action-auto-assign-reviewer@v1
        with:
          reviewers: 'apastan'
