name: 'Auto Assign Dev'
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev

permissions:
  pull-requests: write
  contents: write

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          reviewers-number: 2
          review_assign_method: 'roundRobin'
          reviewers: |
            apastan
            blue-script
            nooraiym
            apelsinom
            olesya-sh-dev
            inctateam